apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "%s-config" (include "server.name" .) }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "server.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  PalWorldSettings.ini: |-
    {{- range $key, $value := .Values.common.serverOptions }}
    {{ (printf "%s=%s" ($key) ($value | toString)) | nindent 4 }}
    {{- end }}