{{- if .Values.serviceAccount.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ default (include "server.name" . ) .Values.serviceAccount.server.name }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.server.annotations }}
    {{ toYaml .Values.serviceAccount.server.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
secrets:
  - name: {{ printf "%s-serviceaccount" (include "server.name" . ) }}
automountServiceAccountToken: true
{{- end }}
